# Generated by Django 2.2.10 on 2021-09-18 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Question', verbose_name='Вопрос'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answeroption',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Question', verbose_name='Вопрос'),
            preserve_default=False,
        ),
    ]
